version: '3.1'

services:
  postgres:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=easyprompts
      - POSTGRES_USER=easyprompts
      - POSTGRES_PASSWORD=easyprompts