-- CreateEnum
CREATE TYPE "MODIFIER_TYPE" AS ENUM ('PREFIX', 'SUFFIX', 'COMPOSABLE');

-- AlterTable
ALTER TABLE "modifiers" ADD COLUMN     "type" "MODIFIER_TYPE" NOT NULL DEFAULT 'SUFFIX';

-- DropEnum
DROP TYPE "CRAFT_TYPE";
